language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t travis-node .
  - docker tag travis-node kimoyobeads/travis_ci_cd_dh:latest

# After success
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export "$FAVORITE_FOOD"
  - export "$FAVORITE_FOOD"
  - docker push kimoyobeads/travis_ci_cd_dh
